// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlite_world_repo

import (
	"time"
)

type World struct {
	WorldID      int64
	DateCreated  time.Time
	RowLength    int64
	ColumnLength int64
	ChunkLength  int64
}

type WorldChunk struct {
	WorldID     int64
	RowID       int64
	ColID       int64
	LastUpdated time.Time
	Locked      bool
	Chunk       []byte
}
